### ISSUE TITLE
Allow custom dimensions

### ISSUE THREAD

**Issue by tvincent2** [ruuda/pris#18]
Hello,

If I understand correctly, the dimensions of the generated pdf files are currently hard-coded to 1920×1080 (e.g. in [pris.rs](https://github.com/ruuda/pris/blob/master/src/bin/pris.rs#L97)).
It would be nice to allow the user to set custom dimensions, for instance using command line parameters or, even better, in `.pris` files themselves.

Thanks a lot for making pris!
Thomas

**Comment by ruuda** [comment]
Yes, the canvas dimensions are currently hard-coded to 1920x1080 pixels. The absolute dimensions are not relevant for screen use (they are for printing), but the aspect ratio is.

I was thinking about exposing a top-level variable like this:

    canvas_size = (1080, 1920)

One tricky thing here is that with Cairo all pages in the document have the same size, so only the last write to the variable would be meaningful, but it would still affect what `1w` and `1h` mean. Perhaps that is not so much of an issue; users should just set the canvas size at the beginning of the document and not change it mid-way. What do you think?

**Comment by tvincent2** [comment]
Your idea for `canvas_size` looks perfect. Just a noob question: Since the absolute dimensions are only relevant for printing, maybe an other unit could be proposed instead of/along pixels?

About the issue of multiple occurrences of `canvas_size`, that's typically the kind of setting that is declared at the beginning of the document, so I would not expect users to change it. Could it be enforced that the variables appears once at most?

**Comment by ruuda** [comment]
Implemented in https://github.com/ruuda/pris/compare/abc05bc...72a5c9d. See also the [new example](https://github.com/ruuda/pris/blob/72a5c9d2daf71ed0d9b9606fdca45b1bf953bd53/examples/canvas_size.pris).

> Just a noob question: Since the absolute dimensions are only relevant for printing, maybe an other unit could be proposed instead of/along pixels?

Yes, that would make sense. For now I am only focusing on screen media though, so `canvas_size` has no units for now.
